f = open("a6.txt", 'rb+')
print(f.tell())
print(f.read(7)) 
print(f.tell())
print(f.read())
print(f.tell())
f.seek(9,0) 
print(f.read(5))
f.seek(4, 1) 
print(f.read(5))
f.seek(-5, 2) 
print(f.read(5))
f.close()